title = "StudioCreator"
gitRepoUrl = "https://github.com/Echo-Innovations/StudioCreator"
organizationName = "Echo-Innovations"
projectName = "StudioCreator"
gitSourceBranch = "main"

[docusaurus]
tagline = "React components for building Roblox Studio plugins"

[footer]
copyright = "Copyright © 2025 Echo-Innovations. Built with Moonwave and Docusaurus."

[home]
enabled = true
includeReadme = true

[[classOrder]]
section = "General"
collapsed = false
classes = ["Constants", "CommonProps"]

[[classOrder]]
section = "Components"
collapsed = false
classes = ["Background", "Button", "Checkbox", "ColorPicker", "DatePicker", "Dropdown", "DropShadowFrame", "Label", "LoadingDots", "MainButton", "NumberSequencePicker", "NumericInput", "PluginProvider", "ProgressBar", "RadioButton", "ScrollFrame", "Slider", "Splitter", "Switch", "TabContainer", "TextInput", "Tooltip"]

[[classOrder]]
section = "Hooks"
collapsed = false
classes = ["useMouseIcon", "useTheme", "usePlugin"]